// @ts-nocheck
import React, { useState, useMemo } from "react";
import { Calculator, Shield, History, Plus, Trash2, Calendar, Target, CheckCircle2 } from "lucide-react";
import { THEME } from "../../utils/constants";
import { fmtINRFull, calcTaxNew, calcTaxOld, today, uid } from "../../utils/finance";
import { Card } from "../ui/Card";
import { Button } from "../ui/Button";
import { Badge } from "../ui/Badge";
import { Field, Input } from "../ui/Form";
import { SectionTitle } from "../ui/SectionTitle";
import { Modal, ModalActions } from "../ui/Modal";

// FY 2025-26 standard deductions
const STD_DED_NEW = 75000;
const STD_DED_OLD = 50000;

/* ══════════════════════════════════════════════════════════════════════
   HELPERS & MODALS
   ══════════════════════════════════════════════════════════════════════ */

const AddTaxPaymentModal = ({ onClose, onSave }: any) => {
  const [f, setF] = useState({ date: today(), type: "TDS", amount: "", note: "" });
  const types = ["TDS", "Advance Tax", "Self-Assessment", "Professional Tax"];

  return (
    <Modal title="Record Tax Payment" onClose={onClose}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label="Payment Date">
          <input className="form-input" type="date" value={f.date} onChange={e => setF({ ...f, date: e.target.value })} />
        </Field>
        <Field label="Type">
          <select className="form-input" value={f.type} onChange={e => setF({ ...f, type: e.target.value })}>
            {types.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
        </Field>
      </div>
      <Field label="Amount (₹)">
        <input className="form-input" type="number" placeholder="0" value={f.amount} onChange={e => setF({ ...f, amount: e.target.value })} />
      </Field>
      <Field label="Note / Reference">
        <input className="form-input" placeholder="e.g. Q2 Advance Tax, Salary TDS" value={f.note} onChange={e => setF({ ...f, note: e.target.value })} />
      </Field>
      <ModalActions onSave={() => f.amount && onSave(f)} onClose={onClose} saveLabel="Record Payment" />
    </Modal>
  );
};

/* ══════════════════════════════════════════════════════════════════════
   MAIN COMPONENT
   ══════════════════════════════════════════════════════════════════════ */

interface TaxVaultTabProps {
  state: any;
  metrics: any;
  addItem: any;
  removeItem: any;
  updateItem: any;
}

export const TaxVaultTab: React.FC<TaxVaultTabProps> = ({ state, metrics, addItem, removeItem }) => {
  const [activeRegime, setActiveRegime] = useState<"new" | "old">(state.profile.regime || "new");
  const [showModal, setShowModal] = useState(false);

  const printTaxSummary = () => {
    const regime = activeRegime === "new" ? "New Regime" : "Old Regime";
    const lines = [
      `TAX SUMMARY — FY ${state.profile.fy}`,
      `Regime: ${regime}`,
      ``,
      `INCOME`,
      `  Annual Income          : ${fmtINRFull(annualIncome)}`,
      `  Standard Deduction     : ${activeRegime === "new" ? fmtINRFull(75000) : fmtINRFull(50000)}`,
      ``,
      `TAX COMPUTATION`,
      `  Gross Tax Liability    : ${fmtINRFull(currentTotalTax)}`,
      `  TDS Already Deducted   : ${fmtINRFull(totalTDS)}`,
      `  Advance Tax Paid       : ${fmtINRFull(totalAdvancePaid)}`,
      `  Remaining Liability    : ${fmtINRFull(remainingAdvance)}`,
      ``,
      `REGIME COMPARISON`,
      `  New Regime Tax         : ${fmtINRFull(taxNew.total)}`,
      `  Old Regime Tax         : ${fmtINRFull(taxOld.total)}`,
      `  Better Choice          : ${taxOld.total < taxNew.total ? "Old Regime" : "New Regime"} (saves ${fmtINRFull(Math.abs(taxNew.total - taxOld.total))})`,
      ``,
      `ADVANCE TAX INSTALMENTS`,
      ...installments.map(i => `  ${i.q} by ${i.due} (${i.pct}%)    : ${fmtINRFull(i.amt)}`),
      ``,
      `Generated by Personal Finance by Anand Mohta`,
    ].join("\n");

    const w = window.open("", "_blank", "width=560,height=680");
    if (w) {
      w.document.write(
        `<html><head><title>Tax Summary FY ${state.profile.fy}</title>` +
        `<style>body{font-family:'Courier New',monospace;padding:40px;background:#0f172a;color:#e2e8f0;font-size:14px;line-height:1.8}` +
        `h2{color:#c5a152;margin-bottom:8px}pre{white-space:pre-wrap;margin:0}` +
        `@media print{body{background:#fff;color:#000}}</style></head>` +
        `<body><h2>Tax Summary — FY ${state.profile.fy}</h2><pre>${lines}</pre>` +
        `<script>setTimeout(()=>window.print(),300);</script></body></html>`
      );
      w.document.close();
    }
  };

  // Controlled deduction state — 80C pre-filled from real state data
  const [deductions, setDeductions] = useState(() => {
    const yearStr = `${new Date().getFullYear()}`;
    const elss = (state.mutualFunds || [])
      .filter((m: any) => (m.type || m.category || "").toUpperCase().includes("ELSS"))
      .reduce((s: number, m: any) => s + Number(m.invested || m.investedAmount || 0), 0);
    const ppfThisYear = (state.ppfLedger || [])
      .filter((t: any) => t.date && t.date.startsWith(yearStr) && t.type !== "withdrawal")
      .reduce((s: number, t: any) => s + Number(t.amount || 0), 0);
    const ppf = ppfThisYear > 0 ? ppfThisYear
      : (state.ppf || []).reduce((s: number, p: any) => s + Number(p.yearlyContribution || p.annualContribution || 0), 0);
    const lic = (state.lic || []).reduce((s: number, l: any) => s + Number(l.annualPremium || 0), 0);
    return {
      d80C: Math.min(elss + ppf + lic, 150000),
      d80D: 25000,
      hra: 0,
      homeLoan: 0,
      nps: 0,
    };
  });

  const setDed = (key: string, val: string) =>
    setDeductions(prev => ({ ...prev, [key]: Number(val) || 0 }));

  // 1. Core Income — use annualIncome (income ledger + FY transactions), not monthIncome * 12
  const annualIncome = metrics.annualIncome || (metrics.monthIncome || 0) * 12;

  // 2. Tax calculations with correct standard deductions
  //    New regime FY 2025-26: ₹75,000 standard deduction before slabs
  const taxableNew = Math.max(0, annualIncome - STD_DED_NEW);
  const taxNew = calcTaxNew(taxableNew);

  //    Old regime: ₹50,000 std deduction + all user-entered deductions
  const totalOldDeductions = STD_DED_OLD + deductions.d80C + deductions.d80D +
    deductions.hra + deductions.homeLoan + deductions.nps;
  const taxOld = calcTaxOld(annualIncome, totalOldDeductions);

  const currentTotalTax = activeRegime === "new" ? taxNew.total : taxOld.total;

  // 3. Advance Tax Logic
  const taxPayments = state.taxPayments || [];
  const totalTDS = taxPayments.filter((p: any) => p.type === "TDS").reduce((s: number, p: any) => s + Number(p.amount || 0), 0);
  const totalAdvancePaid = taxPayments.filter((p: any) => p.type === "Advance Tax").reduce((s: number, p: any) => s + Number(p.amount || 0), 0);
  const totalPaidSoFar = totalTDS + totalAdvancePaid;

  const netLiability = Math.max(0, currentTotalTax - totalTDS);
  const remainingAdvance = Math.max(0, netLiability - totalAdvancePaid);
  const isAdvanceTaxApplicable = netLiability > 10000;

  // Progress — safe against division by zero and overflow
  const progressPct = currentTotalTax > 0
    ? Math.min(100, (totalPaidSoFar / currentTotalTax) * 100)
    : 0;

  // 4. Installments — cumulative percentages of net liability
  const installments = [
    { q: "Q1", due: "15 Jun", pct: 15, amt: netLiability * 0.15 },
    { q: "Q2", due: "15 Sep", pct: 45, amt: netLiability * 0.45 },
    { q: "Q3", due: "15 Dec", pct: 75, amt: netLiability * 0.75 },
    { q: "Q4", due: "15 Mar", pct: 100, amt: netLiability * 1.00 },
  ];

  const handleSavePayment = (data: any) => {
    addItem("taxPayments", { ...data, id: uid() });
    setShowModal(false);
  };

  return (
    <div className="tab-content-enter">
      <SectionTitle
        sub={`Financial Year ${state.profile.fy} · Advance tax tracking & regime comparison`}
        rightElement={
          <div style={{ display: "flex", gap: 8 }}>
            <Button size="sm" variant={activeRegime === "new" ? "accent" : "ghost"} onClick={() => setActiveRegime("new")}>New Regime</Button>
            <Button size="sm" variant={activeRegime === "old" ? "accent" : "ghost"} onClick={() => setActiveRegime("old")}>Old Regime</Button>
          </div>
        }
      >
        Tax Vault
      </SectionTitle>

      {/* ── SUMMARY DASHBOARD ── */}
      <div style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr", gap: 20, marginBottom: 32 }}>
        <Card variant="hero" style={{ padding: 32, display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
          <div>
            <div style={{ fontSize: 10, fontWeight: 800, letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(255,255,255,0.6)", marginBottom: 8 }}>Advance Tax Still to Pay</div>
            <div style={{ fontSize: 52, fontWeight: 900, color: "#fff", marginBottom: 4, letterSpacing: "-0.03em" }}>{fmtINRFull(remainingAdvance)}</div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, color: "rgba(255,255,255,0.7)", fontSize: 13, fontWeight: 500 }}>
              <Shield size={14} /> Total tax: {fmtINRFull(currentTotalTax)} · TDS credited: {fmtINRFull(totalTDS)}
            </div>
          </div>

          <div style={{ marginTop: 32 }}>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "rgba(255,255,255,0.6)", fontWeight: 800, textTransform: "uppercase", marginBottom: 10 }}>
              <span>Progress Paid</span>
              <span>{progressPct.toFixed(0)}%</span>
            </div>
            <div style={{ height: 8, background: "rgba(255,255,255,0.15)", borderRadius: 10, overflow: "hidden" }}>
              <div style={{ height: "100%", width: `${progressPct}%`, background: "#fff", boxShadow: "0 0 15px rgba(255,255,255,0.3)", borderRadius: 10 }} />
            </div>
            <div style={{ display: "flex", gap: 16, marginTop: 16 }}>
              <div>
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.5)", textTransform: "uppercase" }}>TDS Deducted</div>
                <div style={{ fontSize: 16, fontWeight: 800, color: "#fff" }}>{fmtINRFull(totalTDS)}</div>
              </div>
              <div style={{ width: 1, background: "rgba(255,255,255,0.1)" }} />
              <div>
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.5)", textTransform: "uppercase" }}>Advance Paid</div>
                <div style={{ fontSize: 16, fontWeight: 800, color: "#fff" }}>{fmtINRFull(totalAdvancePaid)}</div>
              </div>
            </div>
          </div>
        </Card>

        <Card style={{ padding: 24 }}>
          <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.15em", textTransform: "uppercase", color: THEME.muted, marginBottom: 20 }}>Advance Tax Schedule</div>
          <div style={{ display: "grid", gap: 12 }}>
            {installments.map(inst => {
              const isPaid = totalAdvancePaid >= inst.amt;
              const isPartiallyPaid = totalAdvancePaid > 0 && totalAdvancePaid < inst.amt;

              return (
                <div key={inst.q} style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", borderRadius: 12, background: "rgba(128,128,128,0.03)", border: `1px solid ${THEME.line}` }}>
                  <div style={{ width: 36, height: 36, borderRadius: 10, background: isPaid ? "color-mix(in srgb, var(--t-sage) 12%, transparent)" : "color-mix(in srgb, var(--t-gold) 12%, transparent)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                    {isPaid ? <CheckCircle2 size={18} color={THEME.sage} /> : <Calendar size={18} color={THEME.gold} />}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 800, fontSize: 14 }}>{inst.q} · <span style={{ color: THEME.muted }}>By {inst.due}</span></div>
                    <div style={{ fontSize: 11, color: THEME.muted, fontWeight: 600 }}>Cumulative {inst.pct}% · {fmtINRFull(inst.amt)}</div>
                  </div>
                  {isPaid && <Badge variant="sage" style={{ fontSize: 9 }}>Paid</Badge>}
                  {!isPaid && isPartiallyPaid && <Badge variant="gold" style={{ fontSize: 9 }}>Shortfall</Badge>}
                </div>
              );
            })}
          </div>
          {!isAdvanceTaxApplicable && (
            <div style={{ marginTop: 16, padding: "10px 12px", borderRadius: 10, background: "color-mix(in srgb, var(--t-sage) 8%, transparent)", border: `1px solid color-mix(in srgb, var(--t-sage) 20%, transparent)`, display: "flex", alignItems: "center", gap: 8, fontSize: 11, fontWeight: 600, color: THEME.sage }}>
              <Shield size={14} /> Advance Tax not applicable (Liability &lt; ₹10k)
            </div>
          )}
        </Card>
      </div>

      {/* ── ADVANCE TAX COUNTDOWN ── */}
      {isAdvanceTaxApplicable && (() => {
        const fyParts = (state.profile.fy || "").split("-");
        const fyStartYear = Number(fyParts[0]) || new Date().getFullYear();
        const fyEndYear = fyStartYear + 1;
        const now = new Date();
        const todayMs = now.getTime();

        const instDates = [
          { q: "Q1", label: "1st Instalment", dueDate: new Date(fyStartYear, 5, 15), pct: 15, cumAmt: netLiability * 0.15 },
          { q: "Q2", label: "2nd Instalment", dueDate: new Date(fyStartYear, 8, 15), pct: 45, cumAmt: netLiability * 0.45 },
          { q: "Q3", label: "3rd Instalment", dueDate: new Date(fyStartYear, 11, 15), pct: 75, cumAmt: netLiability * 0.75 },
          { q: "Q4", label: "4th Instalment", dueDate: new Date(fyEndYear, 2, 15), pct: 100, cumAmt: netLiability * 1.00 },
        ];

        const upcoming = instDates.find(i => totalAdvancePaid < i.cumAmt && i.dueDate.getTime() >= todayMs);
        const overdue = instDates.find(i => totalAdvancePaid < i.cumAmt && i.dueDate.getTime() < todayMs);
        const target = upcoming || overdue;
        const allPaid = instDates.every(i => totalAdvancePaid >= i.cumAmt);

        if (allPaid) {
          return (
            <Card style={{ padding: 20, marginBottom: 28, background: "rgba(52,211,153,0.04)", border: "1px solid rgba(52,211,153,0.2)", display: "flex", alignItems: "center", gap: 16 }}>
              <CheckCircle2 size={32} color={THEME.sage} />
              <div>
                <div style={{ fontSize: 15, fontWeight: 800, color: THEME.sage }}>All advance tax payments on track!</div>
                <div style={{ fontSize: 12, color: THEME.muted, marginTop: 2 }}>FY {state.profile.fy} — {fmtINRFull(totalAdvancePaid)} paid of {fmtINRFull(netLiability)} net liability</div>
              </div>
            </Card>
          );
        }

        if (!target) return null;

        const daysLeft = Math.ceil((target.dueDate.getTime() - todayMs) / 86400000);
        const isOverdue = daysLeft < 0;
        const isUrgent = daysLeft >= 0 && daysLeft <= 15;
        const amountDue = Math.max(0, target.cumAmt - totalAdvancePaid);
        const countColor = isOverdue ? THEME.rust : isUrgent ? "#f59e0b" : THEME.sage;
        const dueDateStr = target.dueDate.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });

        return (
          <Card style={{ padding: 24, marginBottom: 28, border: `1.5px solid ${countColor}30` }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>
              <div>
                <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: "0.15em", color: THEME.muted, marginBottom: 4 }}>Advance Tax Countdown</div>
                <div style={{ fontSize: 18, fontWeight: 900, color: THEME.ink }}>{target.label} — {target.q} · {target.pct}% cumulative</div>
                <div style={{ fontSize: 13, color: THEME.muted, marginTop: 4 }}>Due by {dueDateStr}</div>
              </div>
              <div style={{ textAlign: "right", flexShrink: 0 }}>
                <div style={{ fontSize: 48, fontWeight: 900, color: countColor, letterSpacing: "-0.03em", lineHeight: 1 }}>
                  {Math.abs(daysLeft)}
                </div>
                <div style={{ fontSize: 11, fontWeight: 700, color: countColor, textTransform: "uppercase" as const, letterSpacing: "0.1em" }}>
                  {isOverdue ? "days overdue" : "days left"}
                </div>
              </div>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginBottom: 16 }}>
              {[
                { label: "Amount Due Now", value: fmtINRFull(amountDue), color: countColor },
                { label: "Already Paid", value: fmtINRFull(totalAdvancePaid), color: THEME.sage },
                { label: "Net Liability", value: fmtINRFull(netLiability), color: THEME.ink },
              ].map(({ label, value, color }) => (
                <div key={label} style={{ textAlign: "center", padding: "12px 8px", background: "rgba(128,128,128,0.03)", borderRadius: 10, border: `1px solid ${THEME.line}` }}>
                  <div style={{ fontSize: 10, color: THEME.muted, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: "0.04em", marginBottom: 6 }}>{label}</div>
                  <div style={{ fontSize: 16, fontWeight: 900, color }}>{value}</div>
                </div>
              ))}
            </div>

            <div style={{ marginBottom: 8, display: "flex", justifyContent: "space-between", fontSize: 11, color: THEME.muted, fontWeight: 700 }}>
              <span>FY Progress</span>
              <span>{instDates.filter(i => totalAdvancePaid >= i.cumAmt).length} / {instDates.length} instalments done</span>
            </div>
            <div style={{ display: "flex", gap: 6 }}>
              {instDates.map((i) => {
                const paid = totalAdvancePaid >= i.cumAmt;
                const isCurrent = i.q === target.q;
                return (
                  <div key={i.q} style={{ flex: 1, height: 8, borderRadius: 4, background: paid ? THEME.sage : isCurrent ? countColor : THEME.line, opacity: isCurrent && !paid ? 0.85 : 1, transition: "background 0.3s" }} title={`${i.q}: ${i.pct}%`} />
                );
              })}
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", marginTop: 6, fontSize: 10, color: THEME.muted }}>
              {instDates.map(i => <span key={i.q}>{i.q}</span>)}
            </div>

            {isOverdue && (
              <div style={{ marginTop: 14, padding: "10px 14px", borderRadius: 8, background: "rgba(239,68,68,0.06)", border: "1px solid rgba(239,68,68,0.15)", fontSize: 12, color: THEME.rust, fontWeight: 600 }}>
                ⚠️ Overdue by {Math.abs(daysLeft)} days. Interest u/s 234B/234C may apply. Pay immediately.
              </div>
            )}
          </Card>
        );
      })()}

      {/* ── TAX PAYMENTS LOG ── */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <h3 style={{ fontSize: 18, fontWeight: 900, margin: 0, letterSpacing: "-0.02em" }}>Payment Log & TDS</h3>
        <Button size="sm" variant="secondary" icon={<Plus size={14} />} onClick={() => setShowModal(true)}>Record Payment</Button>
      </div>

      {taxPayments.length === 0 ? (
        <Card style={{ padding: "40px 0", textAlign: "center", color: THEME.muted, fontSize: 13 }}>
          No tax payments or TDS entries recorded yet. Use 'Record Payment' to track.
        </Card>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 14, marginBottom: 40 }}>
          {taxPayments.map((p: any) => (
            <Card key={p.id} style={{ padding: "16px 20px", borderLeft: `3px solid ${p.type === "TDS" ? THEME.gold : THEME.sage}` }}>
              <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                <div style={{ width: 40, height: 40, borderRadius: 12, background: "rgba(128,128,128,0.06)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                  <History size={18} color={THEME.muted} />
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 2 }}>
                    <span style={{ fontWeight: 800, fontSize: 15, color: THEME.ink }}>{fmtINRFull(p.amount)}</span>
                    <Badge variant="muted" style={{ fontSize: 9 }}>{p.type}</Badge>
                  </div>
                  <div style={{ fontSize: 11, color: THEME.muted, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {p.date} · {p.note || "No note"}
                  </div>
                </div>
                <Button variant="ghost" size="sm" onClick={() => removeItem("taxPayments", p.id)} style={{ padding: 6, color: THEME.rust }}>
                  <Trash2 size={14} />
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* ── PLANNING SECTION ── */}
      <div style={{ marginBottom: 16 }}>
        <h3 style={{ fontSize: 18, fontWeight: 900, margin: 0, letterSpacing: "-0.02em" }}>Tax Planning & Deductions</h3>
      </div>
      <Card style={{ padding: 32 }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 24 }}>
          <div style={{ gridColumn: "1 / -1", display: "flex", alignItems: "center", gap: 10, borderBottom: `1.5px solid ${THEME.line}`, paddingBottom: 16 }}>
            <Target size={18} color={THEME.accent} />
            <span style={{ fontSize: 13, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.05em", color: THEME.accent }}>Estimated Deductions (Old Regime)</span>
          </div>

          <Field label="80C — LIC, ELSS, PPF (max ₹1.5L)">
            <input className="form-input" type="number" value={deductions.d80C} onChange={e => setDed("d80C", e.target.value)} />
          </Field>
          <Field label="80D — Health Insurance (max ₹25K)">
            <input className="form-input" type="number" value={deductions.d80D} onChange={e => setDed("d80D", e.target.value)} />
          </Field>
          <Field label="HRA Exemption">
            <input className="form-input" type="number" value={deductions.hra} onChange={e => setDed("hra", e.target.value)} />
          </Field>
          <Field label="Home Loan Interest — Sec 24(b) (max ₹2L)">
            <input className="form-input" type="number" value={deductions.homeLoan} onChange={e => setDed("homeLoan", e.target.value)} />
          </Field>
          <Field label="NPS — 80CCD(1B) (max ₹50K)">
            <input className="form-input" type="number" value={deductions.nps} onChange={e => setDed("nps", e.target.value)} />
          </Field>
          <Field label="Standard Deduction (Old Regime)">
            <input className="form-input" type="number" value={STD_DED_OLD} disabled />
          </Field>
        </div>

        <div style={{ marginTop: 40, paddingTop: 32, borderTop: `2px solid ${THEME.line}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div>
            <div style={{ fontSize: 11, color: THEME.muted, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>
              {taxOld.total < taxNew.total ? "Old Regime Saves You" : "New Regime Saves You"}
            </div>
            <div style={{ fontSize: 32, fontWeight: 900, color: THEME.sage }}>
              {fmtINRFull(Math.abs(taxNew.total - taxOld.total))}
            </div>
            <div style={{ fontSize: 12, fontWeight: 600, color: THEME.muted, marginTop: 4 }}>
              New regime tax: {fmtINRFull(taxNew.total)} · Old regime tax: {fmtINRFull(taxOld.total)}
            </div>
          </div>
          <Button variant="accent" size="lg" icon={<Calculator size={20} />} style={{ padding: "12px 40px" }} onClick={printTaxSummary}>Generate Tax Report</Button>
        </div>
      </Card>

      {showModal && <AddTaxPaymentModal onClose={() => setShowModal(false)} onSave={handleSavePayment} />}
    </div>
  );
};
