-- Migration 59: Add breakdown columns to net_worth_history
ALTER TABLE net_worth_history
  ADD COLUMN IF NOT EXISTS cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equity NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS debt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS real_estate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vehicles NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS liabilities NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS breakdown JSONB;
