export const THEME = {
  ink: "var(--t-ink)",
  paper: "var(--t-paper)",
  accent: "var(--t-accent)",
  gold: "var(--t-gold)",
  sage: "var(--t-sage)",
  rust: "var(--t-rust)",
  muted: "var(--t-muted)",
  line: "var(--t-line)",
  darkInk: "var(--t-darkInk)",
  text: "var(--t-ink)",
  textSecondary: "var(--t-muted)",
  card: "var(--t-card-bg)",
  border: "var(--t-line)",
  bg: "var(--t-paper)",
  // Aliases used across several tabs (Govt Schemes, Health Insurance, Bill
  // Payment) that don't have a dedicated semantic-color palette — map them
  // onto the existing brand tokens so they stay theme-aware in light/dark.
  danger: "var(--t-rust)",
  warning: "var(--t-gold)",
  success: "var(--t-sage)",
  primary: "var(--t-accent)",
  textMuted: "var(--t-muted)",
  // Extension colors for charts/legends/avatar sets that need more distinct
  // categories than the 5 semantic colors above provide (e.g. a 6th/7th
  // slice) — fixed hues, not accent-preset-driven, but theme (light/dark)
  // aware via the CSS var.
  violet: "var(--t-violet)",
  pink: "var(--t-pink)",
  cyan: "var(--t-cyan)",
};

// 11 corporate accent colors — one per theme preset (perfect 1:1 mapping).
// Rose removed (not corporate enough per user preference).
export const ACCENT_PALETTES = {
  blue: { light: "#4F46E5", dark: "#818CF8", label: "Indigo", dot: "#4F46E5" },
  purple: { light: "#7C3AED", dark: "#A78BFA", label: "Violet", dot: "#7C3AED" },
  emerald: { light: "#059669", dark: "#34D399", label: "Emerald", dot: "#059669" },
  amber: { light: "#D97706", dark: "#FBBF24", label: "Amber", dot: "#D97706" },
  indigo: { light: "#2563EB", dark: "#60A5FA", label: "Ocean Blue", dot: "#2563EB" },
  navy: { light: "#1E40AF", dark: "#93C5FD", label: "Navy", dot: "#1E40AF" },
  teal: { light: "#0D9488", dark: "#5EEAD4", label: "Teal", dot: "#0D9488" },
  sky: { light: "#0284C7", dark: "#38BDF8", label: "Sky Blue", dot: "#0284C7" },
  forest: { light: "#15803D", dark: "#86EFAC", label: "Forest", dot: "#15803D" },
  crimson: { light: "#B91C1C", dark: "#FCA5A5", label: "Crimson", dot: "#B91C1C" },
  mint: { light: "#0D9F7D", dark: "#10D9A0", label: "Mint", dot: "#10D9A0" },
};

// 22 presets — light & dark for every accent color (perfect 2:1 mapping).
// Matching uses darkMode + accentKey only; fontKey excluded so manually
// changing font does not break the active-preset indicator.
export const THEME_PRESETS = [
  // ── Light (11) ──────────────────────────────────────────────────────────────
  {
    id: "classic",
    label: "Classic",
    description: "Clean indigo on white",
    darkMode: false,
    accentKey: "blue",
    fontKey: "inter",
    bgPreview: "#F8FAFC",
  },
  {
    id: "corporate",
    label: "Corporate",
    description: "Deep navy — executive standard",
    darkMode: false,
    accentKey: "navy",
    fontKey: "inter",
    bgPreview: "#F0F4F8",
  },
  {
    id: "executive",
    label: "Executive",
    description: "Teal precision — modern fintech",
    darkMode: false,
    accentKey: "teal",
    fontKey: "inter",
    bgPreview: "#F0FAFA",
  },
  {
    id: "authority",
    label: "Authority",
    description: "Authoritative red — traditional banking",
    darkMode: false,
    accentKey: "crimson",
    fontKey: "inter",
    bgPreview: "#FFF8F8",
  },
  {
    id: "evergreen",
    label: "Evergreen",
    description: "Forest green — growth & wealth",
    darkMode: false,
    accentKey: "forest",
    fontKey: "outfit",
    bgPreview: "#F0FAF4",
  },
  {
    id: "horizon",
    label: "Horizon",
    description: "Sky blue — clear & focused",
    darkMode: false,
    accentKey: "sky",
    fontKey: "inter",
    bgPreview: "#F0F8FF",
  },
  {
    id: "prestige",
    label: "Prestige",
    description: "Warm amber — premium light",
    darkMode: false,
    accentKey: "amber",
    fontKey: "inter",
    bgPreview: "#FFFBF0",
  },
  {
    id: "lavender",
    label: "Lavender",
    description: "Soft violet — clean & creative",
    darkMode: false,
    accentKey: "purple",
    fontKey: "outfit",
    bgPreview: "#FAF8FF",
  },
  {
    id: "jade",
    label: "Jade",
    description: "Emerald — fresh growth on white",
    darkMode: false,
    accentKey: "emerald",
    fontKey: "inter",
    bgPreview: "#F0FAF6",
  },
  {
    id: "pacific",
    label: "Pacific",
    description: "Ocean blue — calm & professional",
    darkMode: false,
    accentKey: "indigo",
    fontKey: "inter",
    bgPreview: "#F0F4FF",
  },
  {
    id: "nova-light",
    label: "Nova Light",
    description: "Crisp mint — 2026 fintech, daylight",
    darkMode: false,
    accentKey: "mint",
    fontKey: "inter",
    bgPreview: "#F0FBF8",
  },
  // ── Dark (11) ───────────────────────────────────────────────────────────────
  {
    id: "noir",
    label: "Noir",
    description: "Dark indigo — deep professional",
    darkMode: true,
    accentKey: "blue",
    fontKey: "inter",
    bgPreview: "#0D0F18",
  },
  {
    id: "navy-night",
    label: "Navy Night",
    description: "Midnight navy — elite executive",
    darkMode: true,
    accentKey: "navy",
    fontKey: "inter",
    bgPreview: "#080D18",
  },
  {
    id: "aqua",
    label: "Aqua",
    description: "Dark teal — deep fintech terminal",
    darkMode: true,
    accentKey: "teal",
    fontKey: "inter",
    bgPreview: "#041412",
  },
  {
    id: "ember",
    label: "Ember",
    description: "Dark crimson — bold & dramatic",
    darkMode: true,
    accentKey: "crimson",
    fontKey: "inter",
    bgPreview: "#140808",
  },
  {
    id: "canopy",
    label: "Canopy",
    description: "Dark forest — deep wealth & growth",
    darkMode: true,
    accentKey: "forest",
    fontKey: "outfit",
    bgPreview: "#071410",
  },
  {
    id: "bloomberg",
    label: "Bloomberg",
    description: "Dark terminal — sky blue data",
    darkMode: true,
    accentKey: "sky",
    fontKey: "inter",
    bgPreview: "#0B0F1A",
  },
  {
    id: "goldman",
    label: "Goldman",
    description: "Premium dark — gold accent",
    darkMode: true,
    accentKey: "amber",
    fontKey: "inter",
    bgPreview: "#0C0F14",
  },
  {
    id: "midnight",
    label: "Midnight",
    description: "Deep dark — smooth violet",
    darkMode: true,
    accentKey: "purple",
    fontKey: "outfit",
    bgPreview: "#0D0D1A",
  },
  {
    id: "trading",
    label: "Trading",
    description: "Dark emerald — markets & growth",
    darkMode: true,
    accentKey: "emerald",
    fontKey: "inter",
    bgPreview: "#061410",
  },
  {
    id: "carbon",
    label: "Carbon",
    description: "Minimal dark — sharp Roboto type",
    darkMode: true,
    accentKey: "indigo",
    fontKey: "roboto",
    bgPreview: "#111318",
  },
  {
    id: "nova",
    label: "Nova",
    description: "Charcoal & mint — 2026 fintech",
    darkMode: true,
    accentKey: "mint",
    fontKey: "inter",
    bgPreview: "#0B0B0F",
  },
];

export const DENSITY = {
  compact: { cardPad: 16, gap: 12, fontSize: 13, sectionGap: 20 },
  normal: { cardPad: 24, gap: 16, fontSize: 14, sectionGap: 32 },
  comfortable: { cardPad: 32, gap: 24, fontSize: 15, sectionGap: 40 },
};

export const LIGHT_VARS: Record<string, string> = {
  "--t-ink": "#0F172A",
  "--t-paper": "#F8FAFC",
  "--t-accent": "#4F46E5",
  "--t-gold": "#D97706",
  "--t-sage": "#059669",
  "--t-rust": "#DC2626",
  "--t-muted": "#64748B",
  "--t-line": "#E2E8F0",
  "--t-darkInk": "#FFFFFF",
};

export const DARK_VARS: Record<string, string> = {
  "--t-ink": "#E2E8F0",
  "--t-paper": "#0B0F1A",
  "--t-accent": "#818CF8",
  "--t-gold": "#FBBF24",
  "--t-sage": "#34D399",
  "--t-rust": "#FB7185",
  "--t-muted": "#94A3B8",
  "--t-line": "#1E293B",
  "--t-darkInk": "#0F172A",
};

export const PIE_COLORS = [
  "#4F46E5",
  "#059669",
  "#D97706",
  "#DC2626",
  "#7C3AED",
  "#0891B2",
  "#EA580C",
  "#2563EB",
];

export const STORAGE_KEY = "finance_dashboard_v1";
