import { DEFAULT_MASTER_DATA } from "./masterData";
import { getCurrentFY } from "./appConstants";

// Helper to format date offset from today (YYYY-MM-DD)
function offsetDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

function offsetMonths(months: number, dayOfMonth?: number): string {
  const d = new Date();
  d.setMonth(d.getMonth() + months);
  if (dayOfMonth !== undefined) {
    d.setDate(dayOfMonth);
  }
  return d.toISOString().split("T")[0];
}

export const DEMO_USER_SESSION = {
  user: {
    id: "offline-user",
    email: "demo@arthadrishti.internal",
    user_metadata: {
      full_name: "Aarav Sharma",
      display_name: "Demo Account",
      is_demo: true,
    },
    role: "demo",
    aud: "authenticated",
    app_metadata: {
      provider: "demo",
      providers: ["demo"],
    },
  },
  access_token: "demo-token-arthadrishti-offline-mode",
  token_type: "bearer",
  expires_in: 86400 * 365,
  expires_at: Math.floor(Date.now() / 1000) + 86400 * 365,
};

export function isDemoSession(session: any): boolean {
  if (!session?.user) return false;
  return (
    session.user.id === "offline-user" ||
    session.user.email === "demo@arthadrishti.internal" ||
    session.user?.user_metadata?.is_demo === true
  );
}

export function getDemoState(existingSettings?: any): any {
  const todayStr = offsetDays(0);
  const currentFY = getCurrentFY();

  return {
    profile: {
      name: "Aarav",
      fy: currentFY,
      regime: "new",
      savingsTarget: 30,
    },
    masterData: {
      ...DEFAULT_MASTER_DATA,
      _onboardingComplete: true,
      familyProfiles: [
        { id: "self", name: "Aarav Sharma", relation: "Self", relationship: "Self", dob: "1991-08-15" },
        { id: "spouse", name: "Priya Sharma", relation: "Spouse", relationship: "Spouse", dob: "1993-04-22" },
        { id: "father", name: "Rajesh Sharma", relation: "Father", relationship: "Father", dob: "1960-11-10" },
      ],
    },
    settings: existingSettings || {
      darkMode: false,
      accentKey: "blue",
      density: "normal",
      radiusKey: "modern",
      fontKey: "inter",
      bgStyle: "plain",
      animSpeed: "smooth",
      emailEnabled: false,
      emailFrequency: "weekly",
      emailDay: 1,
      emailHour: 8,
      emailAddress: "demo@arthadrishti.internal",
      fromEmail: "",
      geminiApiKey: "",
      goldPricePerGram: 7750,
    },
    bankAccounts: [
      {
        id: "demo-ba-1",
        bankName: "HDFC Bank",
        accountName: "Corporate Salary Account",
        accountNumber: "•••• 4821",
        accountType: "Savings",
        balance: 345000,
        ifsc: "HDFC0000128",
        branch: "Indiranagar, Bengaluru",
        interestRate: 3.5,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
      {
        id: "demo-ba-2",
        bankName: "ICICI Bank",
        accountName: "Emergency & Liquid Stash",
        accountNumber: "•••• 7792",
        accountType: "Savings",
        balance: 215000,
        ifsc: "ICIC0001094",
        branch: "MG Road, Bengaluru",
        interestRate: 3.5,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
      {
        id: "demo-ba-3",
        bankName: "State Bank of India",
        accountName: "Public Sector Ops",
        accountNumber: "•••• 9104",
        accountType: "Savings",
        balance: 95000,
        ifsc: "SBIN0004512",
        branch: "Koramangala, Bengaluru",
        interestRate: 2.7,
        nominee: "Rajesh Sharma",
        nomineeRelation: "Father",
        owner: "self",
      },
      {
        id: "demo-ba-4",
        bankName: "Axis Bank",
        accountName: "Family Pool Account",
        accountNumber: "•••• 3318",
        accountType: "Savings",
        balance: 65000,
        ifsc: "UTIB0000214",
        branch: "Whitefield, Bengaluru",
        interestRate: 3.5,
        nominee: "Aarav Sharma",
        nomineeRelation: "Spouse",
        owner: "spouse",
      },
    ],
    creditCards: [
      {
        id: "demo-cc-1",
        cardName: "HDFC Infinia Metal",
        bank: "HDFC Bank",
        issuer: "HDFC Bank",
        cardNumber: "4111",
        cardType: "Infinia",
        limit: 1000000,
        outstanding: 42500,
        availableLimit: 957500,
        billDate: 15,
        dueDay: 5,
        rewardPoints: 68420,
        owner: "self",
        network: "Visa",
      },
      {
        id: "demo-cc-2",
        cardName: "ICICI Sapphiro",
        bank: "ICICI Bank",
        issuer: "ICICI Bank",
        cardNumber: "8024",
        cardType: "Sapphiro",
        limit: 500000,
        outstanding: 18200,
        availableLimit: 481800,
        billDate: 20,
        dueDay: 10,
        rewardPoints: 24500,
        owner: "self",
        network: "Mastercard",
      },
      {
        id: "demo-cc-3",
        cardName: "Axis Atlas Travel",
        bank: "Axis Bank",
        issuer: "Axis Bank",
        cardNumber: "9910",
        cardType: "Atlas",
        limit: 400000,
        outstanding: 12000,
        availableLimit: 388000,
        billDate: 25,
        dueDay: 15,
        rewardPoints: 14200,
        owner: "self",
        network: "Visa",
      },
    ],
    prepaidCards: [
      {
        id: "demo-pc-1",
        cardName: "Niyo Global Forex",
        bank: "SBM Bank",
        last4: "5512",
        balance: 35000,
        owner: "self",
        status: "Active",
        transactions: [
          { id: "demo-pct-1", date: offsetDays(-5), amount: 4500, description: "Forex FX Booking", type: "spend" },
          { id: "demo-pct-2", date: offsetDays(-20), amount: 40000, description: "Bank Transfer Topup", type: "load" },
        ],
      },
    ],
    demat: [
      {
        id: "demo-dm-1",
        broker: "Zerodha",
        brokerName: "Zerodha Kite",
        accountNumber: "1208160012345678",
        depository: "CDSL",
        dpId: "IN300126",
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
      {
        id: "demo-dm-2",
        broker: "Groww",
        brokerName: "Groww Invest",
        accountNumber: "1208880098765432",
        depository: "CDSL",
        dpId: "IN302927",
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "spouse",
      },
    ],
    mutualFunds: [
      {
        id: "demo-mf-1",
        name: "Parag Parikh Flexi Cap Fund Direct Growth",
        scheme: "Parag Parikh Flexi Cap Fund",
        category: "Flexi Cap",
        folioNumber: "PPFAS/108924",
        units: 2450.5,
        buyNav: 58.4,
        currentNav: 84.65,
        invested: 143109,
        sipAmount: 15000,
        sipDate: 5,
        owner: "self",
        dematId: "demo-dm-1",
      },
      {
        id: "demo-mf-2",
        name: "UTI Nifty 50 Index Fund Direct Growth",
        scheme: "UTI Nifty 50 Index Fund",
        category: "Index Fund",
        folioNumber: "UTI/902144",
        units: 1820.0,
        buyNav: 142.1,
        currentNav: 192.4,
        invested: 258622,
        sipAmount: 10000,
        sipDate: 10,
        owner: "self",
        dematId: "demo-dm-1",
      },
      {
        id: "demo-mf-3",
        name: "Quant Mid Cap Fund Direct Growth",
        scheme: "Quant Mid Cap Fund",
        category: "Mid Cap",
        folioNumber: "QNT/441029",
        units: 920.0,
        buyNav: 190.5,
        currentNav: 278.5,
        invested: 175260,
        sipAmount: 7500,
        sipDate: 15,
        owner: "self",
        dematId: "demo-dm-1",
      },
      {
        id: "demo-mf-4",
        name: "Mirae Asset Large Cap Fund Direct Growth",
        scheme: "Mirae Asset Large Cap Fund",
        category: "Large Cap",
        folioNumber: "MIR/650123",
        units: 1500.0,
        buyNav: 88.0,
        currentNav: 119.5,
        invested: 132000,
        sipAmount: 5000,
        sipDate: 1,
        owner: "self",
        dematId: "demo-dm-1",
      },
      {
        id: "demo-mf-5",
        name: "Nippon India Small Cap Fund Direct Growth",
        scheme: "Nippon India Small Cap Fund",
        category: "Small Cap",
        folioNumber: "NIP/887410",
        units: 880.4,
        buyNav: 112.0,
        currentNav: 168.2,
        invested: 98604,
        sipAmount: 5000,
        sipDate: 20,
        owner: "spouse",
        dematId: "demo-dm-2",
      },
    ],
    stocks: [
      {
        id: "demo-stk-1",
        symbol: "RELIANCE.NS",
        name: "Reliance Industries Ltd",
        exchange: "NSE",
        qty: 65,
        avgPrice: 2420,
        currentPrice: 2985,
        sector: "Energy & Conglomerate",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-2",
        symbol: "TCS.NS",
        name: "Tata Consultancy Services Ltd",
        exchange: "NSE",
        qty: 45,
        avgPrice: 3450,
        currentPrice: 4150,
        sector: "Technology & IT",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-3",
        symbol: "HDFCBANK.NS",
        name: "HDFC Bank Ltd",
        exchange: "NSE",
        qty: 120,
        avgPrice: 1510,
        currentPrice: 1755,
        sector: "Banking & Financials",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-4",
        symbol: "INFY.NS",
        name: "Infosys Ltd",
        exchange: "NSE",
        qty: 85,
        avgPrice: 1420,
        currentPrice: 1890,
        sector: "Technology & IT",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-5",
        symbol: "ITC.NS",
        name: "ITC Ltd",
        exchange: "NSE",
        qty: 200,
        avgPrice: 380,
        currentPrice: 495,
        sector: "FMCG",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-6",
        symbol: "LT.NS",
        name: "Larsen & Toubro Ltd",
        exchange: "NSE",
        qty: 35,
        avgPrice: 3100,
        currentPrice: 3780,
        sector: "Infrastructure & Engineering",
        dematId: "demo-dm-1",
        owner: "self",
      },
      {
        id: "demo-stk-7",
        symbol: "TATAMOTORS.NS",
        name: "Tata Motors Ltd",
        exchange: "NSE",
        qty: 110,
        avgPrice: 720,
        currentPrice: 975,
        sector: "Automobile",
        dematId: "demo-dm-2",
        owner: "spouse",
      },
    ],
    fixedDeposits: [
      {
        id: "demo-fd-1",
        bankName: "HDFC Bank",
        accountNumber: "FD/991048",
        principal: 500000,
        amount: 500000,
        interestRate: 7.25,
        startDate: offsetMonths(-4),
        maturityDate: offsetMonths(8),
        maturityAmount: 537500,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
      {
        id: "demo-fd-2",
        bankName: "State Bank of India",
        accountNumber: "SBI/FD/5521",
        principal: 150000,
        amount: 150000,
        interestRate: 6.8,
        startDate: offsetMonths(-14),
        maturityDate: offsetMonths(46),
        maturityAmount: 215000,
        taxSaver: true,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
    ],
    recurringDeposits: [
      {
        id: "demo-rd-1",
        bankName: "ICICI Bank",
        accountNumber: "RD/882190",
        monthly: 15000,
        rate: 7.1,
        tenureMonths: 24,
        startDate: offsetMonths(-8),
        maturityAmount: 388500,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
    ],
    bonds: [
      {
        id: "demo-bnd-1",
        name: "Bharat Bond ETF 2030 (AAA Govt Backed)",
        totalInvestmentAmount: 200000,
        couponRate: 7.5,
        faceValue: 200000,
        maturityDate: "2030-04-15",
        issuer: "Edelweiss / Govt PSU",
        owner: "self",
      },
      {
        id: "demo-bnd-2",
        name: "RBI Floating Rate Savings Bonds (FRSB)",
        totalInvestmentAmount: 150000,
        couponRate: 8.05,
        faceValue: 150000,
        maturityDate: "2031-10-01",
        issuer: "Reserve Bank of India",
        owner: "self",
      },
    ],
    ppf: [
      {
        id: "demo-ppf-1",
        bank: "State Bank of India",
        accountNumber: "PPF-30881924",
        balance: 840000,
        currentBalance: 840000,
        annualContribution: 150000,
        maturityDate: "2034-03-31",
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
    ],
    epf: [
      {
        id: "demo-epf-1",
        establishmentName: "Enterprise Software & Tech India Pvt Ltd",
        uan: "100918273645",
        memberId: "KN/BNG/0045123/000/00912",
        totalBalance: 1485000,
        balance: 1485000,
        employeeShare: 720000,
        employerShare: 545000,
        pensionShare: 220000,
        interestRate: 8.25,
        owner: "self",
        transactions: [
          {
            id: "demo-epft-1",
            date: offsetDays(-5),
            wageMonth: "Previous Month",
            employeeAmount: 18000,
            employerAmount: 12500,
            pensionAmount: 1250,
          },
          {
            id: "demo-epft-2",
            date: offsetDays(-35),
            wageMonth: "Two Months Ago",
            employeeAmount: 18000,
            employerAmount: 12500,
            pensionAmount: 1250,
          },
        ],
      },
    ],
    nps: [
      {
        id: "demo-nps-1",
        pran: "110098451234",
        fundManager: "HDFC Pension Fund Management",
        tier: "Tier 1",
        balance: 725000,
        currentCorpus: 725000,
        equityAllocation: 65,
        debtAllocation: 35,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
    ],
    realEstateProperties: [
      {
        id: "demo-re-1",
        name: "Sobha Dream Acres 3BHK Residence",
        type: "Residential",
        propertyType: "Apartment",
        purchasePrice: 11000000,
        currentValuation: 15500000,
        location: "Panathur Main Road, Whitefield, Bengaluru",
        areaSqFt: 1580,
        purchaseDate: "2021-06-15",
        owner: "self",
        owners: [
          { id: "self", sharePct: 60 },
          { id: "spouse", sharePct: 40 },
        ],
      },
      {
        id: "demo-re-2",
        name: "Brigade Meadows 2BHK Rental Asset",
        type: "Rental Property",
        propertyType: "Apartment",
        purchasePrice: 5800000,
        currentValuation: 8800000,
        location: "Kanakapura Road, Bengaluru",
        areaSqFt: 1150,
        purchaseDate: "2019-11-20",
        owner: "self",
        rentalStatus: "Rented",
      },
    ],
    rentalProperties: [
      {
        id: "demo-rent-1",
        propertyName: "Brigade Meadows 2BHK Rental Asset",
        tenantName: "Vikas Reddy",
        monthlyRent: 34000,
        securityDeposit: 150000,
        leaseStart: "2024-04-01",
        leaseEnd: "2025-03-31",
        rentDueDay: 5,
        maintenanceIncluded: false,
        owner: "self",
      },
    ],
    loansTaken: [
      {
        id: "demo-ln-1",
        name: "HDFC Home Loan (Sobha 3BHK)",
        lender: "HDFC Bank",
        loanType: "Home Loan",
        principal: 7500000,
        outstanding: 5120000,
        interestRate: 8.45,
        emi: 64800,
        tenureMonths: 240,
        emiDay: 10,
        startDate: "2021-07-10",
        owner: "self",
        taxBenefit80C: true,
        taxBenefit24: true,
      },
      {
        id: "demo-ln-2",
        name: "ICICI Car Loan (Hyundai Creta)",
        lender: "ICICI Bank",
        loanType: "Vehicle Loan",
        principal: 900000,
        outstanding: 340000,
        interestRate: 8.75,
        emi: 18500,
        tenureMonths: 60,
        emiDay: 5,
        startDate: "2022-09-05",
        owner: "self",
      },
    ],
    loansGiven: [
      {
        id: "demo-lg-1",
        borrowerName: "Aditya Verma (Colleague)",
        borrowerPhone: "+91 98450 11223",
        amount: 75000,
        interestRate: 0,
        startDate: offsetMonths(-3),
        expectedReturnDate: offsetMonths(3),
        notes: "Emergency personal advance",
        owner: "self",
      },
    ],
    subscriptions: [
      {
        id: "demo-sub-1",
        name: "Netflix Premium 4K",
        category: "Entertainment",
        amount: 649,
        billingCycle: "monthly",
        nextDueDate: offsetDays(12),
        serviceProvider: "Netflix",
        paymentMethod: "HDFC Infinia",
        owner: "self",
      },
      {
        id: "demo-sub-2",
        name: "Spotify Family HiFi",
        category: "Entertainment",
        amount: 179,
        billingCycle: "monthly",
        nextDueDate: offsetDays(18),
        serviceProvider: "Spotify",
        paymentMethod: "HDFC Infinia",
        owner: "self",
      },
      {
        id: "demo-sub-3",
        name: "Amazon Prime Annual",
        category: "Shopping",
        amount: 1499,
        billingCycle: "yearly",
        nextDueDate: offsetDays(85),
        serviceProvider: "Amazon",
        paymentMethod: "ICICI Sapphiro",
        owner: "self",
      },
      {
        id: "demo-sub-4",
        name: "Cult.fit Elite Annual",
        category: "Health & Fitness",
        amount: 16500,
        billingCycle: "yearly",
        nextDueDate: offsetDays(140),
        serviceProvider: "Cult.fit",
        paymentMethod: "HDFC Infinia",
        owner: "self",
      },
      {
        id: "demo-sub-5",
        name: "Claude Pro & AI Workspace",
        category: "Productivity",
        amount: 3999,
        billingCycle: "monthly",
        nextDueDate: offsetDays(6),
        serviceProvider: "Anthropic",
        paymentMethod: "HDFC Infinia",
        owner: "self",
      },
    ],
    budgets: [
      { id: "demo-bg-1", category: "Food & Groceries", monthlyLimit: 30000, spent: 18450 },
      { id: "demo-bg-2", category: "Transport & Fuel", monthlyLimit: 12000, spent: 7800 },
      { id: "demo-bg-3", category: "Utilities & Bills", monthlyLimit: 15000, spent: 9200 },
      { id: "demo-bg-4", category: "Shopping & Lifestyle", monthlyLimit: 25000, spent: 14600 },
      { id: "demo-bg-5", category: "Entertainment & Dining", monthlyLimit: 18000, spent: 11200 },
      { id: "demo-bg-6", category: "Health & Wellness", monthlyLimit: 10000, spent: 3400 },
    ],
    income: [
      {
        id: "demo-inc-1",
        source: "Enterprise Tech - Primary Salary",
        category: "Salary",
        amount: 265000,
        frequency: "monthly",
        receivedDate: 1,
        creditedToAccount: "demo-ba-1",
        taxDeducted: 42000,
        owner: "self",
      },
      {
        id: "demo-inc-2",
        source: "Brigade Meadows Apartment Rental",
        category: "Rent",
        amount: 34000,
        frequency: "monthly",
        receivedDate: 5,
        creditedToAccount: "demo-ba-2",
        owner: "self",
      },
      {
        id: "demo-inc-3",
        source: "Fintech Advisory & Architecture",
        category: "Freelance / Consulting",
        amount: 65000,
        frequency: "quarterly",
        receivedDate: 15,
        creditedToAccount: "demo-ba-1",
        owner: "self",
      },
      {
        id: "demo-inc-4",
        source: "Portfolio Equity & Fund Dividends",
        category: "Dividends",
        amount: 8500,
        frequency: "monthly",
        receivedDate: 28,
        creditedToAccount: "demo-ba-1",
        owner: "self",
      },
    ],
    sips: [
      {
        id: "demo-sip-1",
        fundName: "Parag Parikh Flexi Cap Fund",
        amount: 15000,
        debitDay: 5,
        bankAccount: "demo-ba-1",
        folio: "PPFAS/108924",
        status: "Active",
        frequency: "Monthly",
        startDate: "2022-01-05",
        owner: "self",
      },
      {
        id: "demo-sip-2",
        fundName: "UTI Nifty 50 Index Fund",
        amount: 10000,
        debitDay: 10,
        bankAccount: "demo-ba-1",
        folio: "UTI/902144",
        status: "Active",
        frequency: "Monthly",
        startDate: "2022-03-10",
        owner: "self",
      },
      {
        id: "demo-sip-3",
        fundName: "Quant Mid Cap Fund",
        amount: 7500,
        debitDay: 15,
        bankAccount: "demo-ba-2",
        folio: "QNT/441029",
        status: "Active",
        frequency: "Monthly",
        startDate: "2023-05-15",
        owner: "self",
      },
      {
        id: "demo-sip-4",
        fundName: "Mirae Asset Large Cap Fund",
        amount: 5000,
        debitDay: 1,
        bankAccount: "demo-ba-1",
        folio: "MIR/650123",
        status: "Active",
        frequency: "Monthly",
        startDate: "2022-06-01",
        owner: "self",
      },
    ],
    goals: [
      {
        id: "demo-gl-1",
        name: "Financial Independence (FIRE Corpus)",
        category: "Retirement",
        targetAmount: 60000000,
        currentAmount: 21850000,
        targetDate: "2038-12-31",
        priority: "High",
        owner: "self",
      },
      {
        id: "demo-gl-2",
        name: "Swiss Alps & Europe Family Trip",
        category: "Travel",
        targetAmount: 650000,
        currentAmount: 480000,
        targetDate: offsetMonths(7),
        priority: "Medium",
        owner: "self",
      },
      {
        id: "demo-gl-3",
        name: "Child Higher Education Fund",
        category: "Education",
        targetAmount: 5000000,
        currentAmount: 1650000,
        targetDate: "2036-06-30",
        priority: "High",
        owner: "self",
      },
      {
        id: "demo-gl-4",
        name: "EV Luxury Upgrade (BMW i4 / Tesla)",
        category: "Vehicle",
        targetAmount: 4500000,
        currentAmount: 1200000,
        targetDate: "2028-03-31",
        priority: "Low",
        owner: "self",
      },
    ],
    goldHoldings: [
      {
        id: "demo-gh-1",
        type: "SGB",
        name: "Sovereign Gold Bond 2026 Series III",
        weightGrams: 50,
        purchasePrice: 4850,
        currentValue: 387500,
        certificateNumber: "SGB/2026/09124",
        maturityDate: "2026-11-25",
        interestRate: 2.5,
        owner: "self",
      },
      {
        id: "demo-gh-2",
        type: "Digital Gold",
        name: "MMTC-PAMP 24K 999.9 Fine Gold",
        weightGrams: 25,
        purchasePrice: 5900,
        currentValue: 193750,
        lockerId: "MMTC-991204",
        owner: "spouse",
      },
    ],
    vehicles: [
      {
        id: "demo-vh-1",
        name: "Hyundai Creta SX (O) 1.5 Turbo",
        vehicleType: "Four Wheeler",
        registrationNumber: "KA 03 MX 4892",
        purchaseYear: 2022,
        purchasePrice: 1850000,
        currentValuation: 1380000,
        insuranceExpiry: offsetMonths(5),
        fuelType: "Petrol",
        owner: "self",
      },
      {
        id: "demo-vh-2",
        name: "Ather 450X Gen 3 EV Scooter",
        vehicleType: "Two Wheeler",
        registrationNumber: "KA 51 EB 1104",
        purchaseYear: 2023,
        purchasePrice: 165000,
        currentValuation: 125000,
        insuranceExpiry: offsetMonths(8),
        fuelType: "Electric",
        owner: "self",
      },
    ],
    healthInsurance: [
      {
        id: "demo-hi-1",
        policyName: "HDFC ERGO Optima Secure Family Floater",
        provider: "HDFC ERGO",
        policyNumber: "2819/009182/2024",
        sumInsured: 2500000,
        premium: 32500,
        renewalDate: offsetMonths(4),
        membersCovered: "Self (Aarav), Spouse (Priya), Child (Ananya)",
        tpa: "In-House Claim Support",
        owner: "self",
      },
      {
        id: "demo-hi-2",
        policyName: "Star Health Senior Citizens Red Carpet",
        provider: "Star Health",
        policyNumber: "STAR/SR/881290",
        sumInsured: 1000000,
        premium: 48000,
        renewalDate: offsetMonths(9),
        membersCovered: "Father (Rajesh Sharma)",
        tpa: "Star In-House",
        owner: "father",
      },
    ],
    termPlans: [
      {
        id: "demo-tp-1",
        policyName: "Max Life Smart Secure Plus",
        provider: "Max Life Insurance",
        policyNumber: "MAX/TRM/9981240",
        sumAssured: 25000000,
        annualPremium: 26500,
        renewalDate: offsetMonths(6),
        termYears: 35,
        coverTillAge: 65,
        nominee: "Priya Sharma",
        nomineeRelation: "Spouse",
        owner: "self",
      },
    ],
    creditScores: [
      {
        id: "demo-cs-1",
        bureau: "CIBIL",
        score: 815,
        checkDate: offsetDays(-10),
        asOfDate: offsetDays(-10),
        source: "CIBIL Direct",
        notes: "Prime tier score",
        rating: "Excellent",
        status: "Active",
        maxScore: 900,
        creditAge: "9 yrs 4 mo",
        onTimePaymentsPct: 100,
        owner: "self",
      },
      {
        id: "demo-cs-2",
        bureau: "Experian",
        score: 838,
        checkDate: offsetDays(-15),
        asOfDate: offsetDays(-15),
        source: "CRED",
        notes: "Consistent clean repayment history",
        rating: "Exceptional",
        status: "Active",
        maxScore: 900,
        creditAge: "9 yrs 4 mo",
        onTimePaymentsPct: 100,
        owner: "self",
      },
      {
        id: "demo-cs-3",
        bureau: "CIBIL",
        score: 795,
        checkDate: offsetDays(-120),
        asOfDate: offsetDays(-120),
        source: "Paisabazaar",
        notes: "Previous quarter check",
        rating: "Excellent",
        status: "Active",
        maxScore: 900,
        creditAge: "9 yrs",
        onTimePaymentsPct: 100,
        owner: "self",
      },
      {
        id: "demo-cs-4",
        bureau: "Experian",
        score: 820,
        checkDate: offsetDays(-135),
        asOfDate: offsetDays(-135),
        source: "BankApp",
        notes: "Previous check",
        rating: "Excellent",
        status: "Active",
        maxScore: 900,
        creditAge: "9 yrs",
        onTimePaymentsPct: 100,
        owner: "self",
      },
    ],
    reminders: [
      {
        id: "demo-rem-1",
        title: "HDFC Infinia Statement Payment",
        category: "Credit Card",
        dueDate: offsetDays(4),
        amount: 42500,
        status: "Pending",
        priority: "High",
        recurring: "Monthly",
        owner: "self",
      },
      {
        id: "demo-rem-2",
        title: "Advance Tax Q3 Installment Due",
        category: "Tax",
        dueDate: offsetDays(18),
        amount: 45000,
        status: "Pending",
        priority: "High",
        recurring: "Quarterly",
        owner: "self",
      },
      {
        id: "demo-rem-3",
        title: "HDFC ERGO Health Insurance Renewal",
        category: "Insurance",
        dueDate: offsetMonths(4),
        amount: 32500,
        status: "Upcoming",
        priority: "Medium",
        recurring: "Yearly",
        owner: "self",
      },
      {
        id: "demo-rem-4",
        title: "Mutual Fund Monthly SIP Auto-Debit",
        category: "Investment",
        dueDate: offsetDays(2),
        amount: 37500,
        status: "Pending",
        priority: "High",
        recurring: "Monthly",
        owner: "self",
      },
    ],
    dividends: [
      {
        id: "demo-div-1",
        companyName: "Tata Consultancy Services Ltd",
        stockSymbol: "TCS",
        grossAmount: 3850,
        tdsAmount: 385,
        netAmount: 3465,
        paymentDate: offsetDays(-22),
        financialYear: currentFY,
        owner: "self",
      },
      {
        id: "demo-div-2",
        companyName: "ITC Ltd",
        stockSymbol: "ITC",
        grossAmount: 4125,
        tdsAmount: 412,
        netAmount: 3713,
        paymentDate: offsetDays(-50),
        financialYear: currentFY,
        owner: "self",
      },
      {
        id: "demo-div-3",
        companyName: "Infosys Ltd",
        stockSymbol: "INFY",
        grossAmount: 2275,
        tdsAmount: 227,
        netAmount: 2048,
        paymentDate: offsetDays(-75),
        financialYear: currentFY,
        owner: "self",
      },
    ],
    transactions: [
      {
        id: "demo-tx-1",
        date: offsetDays(-1),
        amount: 3450,
        category: "Food",
        type: "debit",
        description: "Nature's Basket Organic Groceries",
        note: "Weekly groceries & pantry refill",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-2",
        date: offsetDays(-2),
        amount: 1850,
        category: "Entertainment",
        type: "debit",
        description: "PVR Directors Cut - IMAX Movie & Snacks",
        note: "Weekend cinema with family",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-3",
        date: offsetDays(-3),
        amount: 265000,
        category: "Salary",
        type: "credit",
        description: "Enterprise Tech - Monthly Salary Credit",
        note: "Net monthly compensation",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-4",
        date: offsetDays(-4),
        amount: 34000,
        category: "Rent",
        type: "credit",
        description: "Brigade Meadows Rental - Vikas Reddy",
        note: "Monthly residential rent",
        bankAccountId: "demo-ba-2",
      },
      {
        id: "demo-tx-5",
        date: offsetDays(-5),
        amount: 15000,
        category: "Investment",
        type: "debit",
        description: "SIP Debit: Parag Parikh Flexi Cap Fund",
        note: "Auto-debit SIP Folio 108924",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-6",
        date: offsetDays(-6),
        amount: 64800,
        category: "EMI",
        type: "debit",
        description: "HDFC Home Loan EMI Auto-Debit",
        note: "Sobha 3BHK Loan Repayment",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-7",
        date: offsetDays(-7),
        amount: 4200,
        category: "Transport",
        type: "debit",
        description: "Shell Fuel Station Auto Fuel",
        note: "Creta Tank Refill",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-8",
        date: offsetDays(-8),
        amount: 2890,
        category: "Bills",
        type: "debit",
        description: "BESCOM Electricity Bill Payment",
        note: "Apartment Monthly Power Bill",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-9",
        date: offsetDays(-9),
        amount: 10000,
        category: "Investment",
        type: "debit",
        description: "SIP Debit: UTI Nifty 50 Index Fund",
        note: "Auto-debit SIP Folio 902144",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-10",
        date: offsetDays(-11),
        amount: 7500,
        category: "Investment",
        type: "debit",
        description: "SIP Debit: Quant Mid Cap Fund",
        note: "Auto-debit SIP Folio 441029",
        bankAccountId: "demo-ba-2",
      },
      {
        id: "demo-tx-11",
        date: offsetDays(-12),
        amount: 5400,
        category: "Shopping",
        type: "debit",
        description: "Amazon India Online Order",
        note: "Home appliances & desk setup",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-12",
        date: offsetDays(-14),
        amount: 18500,
        category: "EMI",
        type: "debit",
        description: "ICICI Car Loan EMI Auto-Debit",
        note: "Creta Car Loan installment",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-13",
        date: offsetDays(-16),
        amount: 3465,
        category: "Investment",
        type: "credit",
        description: "TCS Quarterly Dividend Credit",
        note: "Dividend on 45 shares @ Rs 77/sh",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-14",
        date: offsetDays(-18),
        amount: 1450,
        category: "Bills",
        type: "debit",
        description: "ACT Fibernet Broadband Bill",
        note: "Gigabit fiber internet plan",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-15",
        date: offsetDays(-21),
        amount: 3999,
        category: "Bills",
        type: "debit",
        description: "Anthropic Claude Pro Subscription",
        note: "AI dev workspace",
        bankAccountId: "demo-ba-1",
      },
      {
        id: "demo-tx-16",
        date: offsetDays(-25),
        amount: 8200,
        category: "Food",
        type: "debit",
        description: "Toit Brewpub Dinner & Dining",
        note: "Team dinner & celebrations",
        bankAccountId: "demo-ba-1",
      },
    ],
    netWorthHistory: [
      { date: offsetMonths(-11, 1), netWorth: 17200000 },
      { date: offsetMonths(-10, 1), netWorth: 17650000 },
      { date: offsetMonths(-9, 1), netWorth: 18100000 },
      { date: offsetMonths(-8, 1), netWorth: 18550000 },
      { date: offsetMonths(-7, 1), netWorth: 19020000 },
      { date: offsetMonths(-6, 1), netWorth: 19480000 },
      { date: offsetMonths(-5, 1), netWorth: 19950000 },
      { date: offsetMonths(-4, 1), netWorth: 20450000 },
      { date: offsetMonths(-3, 1), netWorth: 20950000 },
      { date: offsetMonths(-2, 1), netWorth: 21400000 },
      { date: offsetMonths(-1, 1), netWorth: 21850000 },
      { date: todayStr, netWorth: 22350000 },
    ],
    documents: [
      {
        id: "demo-doc-1",
        name: "PAN Card - Aarav Sharma",
        category: "Identity",
        documentNumber: "ABCPS1234D",
        expiryDate: "2099-12-31",
        notes: "Primary IT Dept PAN",
      },
      {
        id: "demo-doc-2",
        name: "Passport - Aarav Sharma",
        category: "Travel",
        documentNumber: "Z9182345",
        expiryDate: "2032-05-18",
        notes: "36-page Indian Passport",
      },
      {
        id: "demo-doc-3",
        name: "Max Life Term Insurance Policy Document",
        category: "Insurance",
        documentNumber: "MAX/TRM/9981240",
        expiryDate: "2056-08-15",
        notes: "Rs 2.5 Cr Term Life Cover Bond",
      },
      {
        id: "demo-doc-4",
        name: "Sobha Dream Acres Sale Deed & Khata Extract",
        category: "Property",
        documentNumber: "REG/2021/BLR/912",
        expiryDate: "2099-12-31",
        notes: "A-Khata Registered Deed",
      },
    ],
    taxPayments: [
      {
        id: "demo-tax-1",
        financialYear: currentFY,
        assessmentYear: "2025-26",
        installment: "Q1 (15%)",
        amount: 35000,
        paymentDate: offsetMonths(-4, 14),
        challanNumber: "CHL/918234/2024",
        bsrCode: "000214",
      },
      {
        id: "demo-tax-2",
        financialYear: currentFY,
        assessmentYear: "2025-26",
        installment: "Q2 (45%)",
        amount: 45000,
        paymentDate: offsetMonths(-1, 12),
        challanNumber: "CHL/984512/2024",
        bsrCode: "000214",
      },
    ],
    govtSchemes: [
      {
        id: "demo-gs-1",
        schemeName: "Sovereign Gold Bonds (SGB)",
        schemeType: "SGB",
        accountNumber: "SGB-2026-III-0912",
        investedAmount: 242500,
        currentBalance: 387500,
        interestRate: 2.5,
        maturityDate: "2026-11-25",
        owner: "self",
      },
    ],
    salarySlips: [
      {
        id: "demo-ss-1",
        month: offsetMonths(-1, 1).substring(0, 7),
        basic: 125000,
        hra: 50000,
        specialAllowance: 90000,
        pfEmployee: 18000,
        taxDeducted: 42000,
        netPay: 205000,
        employerName: "Enterprise Software & Tech India Pvt Ltd",
        owner: "self",
      },
    ],
    corporateActions: [],
    lic: [],
    investmentPlans: [],
    informalBorrowed: [],
    informalLent: [],
    rentedProperties: [],
    wishlists: [],
    wishlistItems: [],
    realEstateDemands: [],
    realEstatePayments: [],
    lifeEvents: [],
    billPayments: [
      {
        id: "demo-bp-1",
        billerName: "BESCOM Bangalore Electricity",
        category: "Electricity",
        consumerNumber: "192837465",
        averageBill: 2900,
        dueDateDay: 15,
        owner: "self",
      },
      {
        id: "demo-bp-2",
        billerName: "ACT Fibernet Broadband",
        category: "Internet",
        consumerNumber: "ACT-BNG-88120",
        averageBill: 1450,
        dueDateDay: 18,
        owner: "self",
      },
    ],
    billPaymentHistory: [],
    recurringExpenses: [],
    stockSells: [],
    mfSells: [],
    form26as: [],
    dismissedAlerts: {},
  };
}
